import { ConfigurationSchema } from './types';

export const DEFAULT_CONFIGURATION = Object.freeze<ConfigurationSchema>({
  schemaVersion: 1,

  skipReleaseNotes: false,

  jpdbApiToken: '',
  jpdbMiningDeck: '',
  jpdbBlacklistDeck: 'blacklist',
  jpdbNeverForgetDeck: 'never-forget',
  jpdbForqDeck: 'forq',
  jpdbSuspendDeck: '',
  jpdbAddToForq: false,
  jpdbUseTwoGrades: false,
  jpdbDisableReviews: false,
  jpdbReviewNothing: [],
  jpdbReviewSomething: [],
  jpdbReviewHard: [],
  jpdbReviewOkay: [],
  jpdbReviewEasy: [],
  jpdbReviewFail: [],
  jpdbReviewPass: [],
  jpdbRotateForward: [],
  jpdbRotateBackward: [],

  jpdbRotateFlags: false,
  jpdbRotateCycle: false,
  jpdbCycleNeverForget: true,
  jpdbCycleBlacklist: true,
  jpdbCycleSuspended: false,

  useLegacyHighlighter: false,
  skipFurigana: false,
  generatePitch: false,
  showCurrentOnTop: true,
  hideInactiveTabs: true,

  enableAnkiIntegration: false,
  ankiUrl: 'http://localhost:8765',
  ankiProxyUrl: '',
  ankiMiningConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  ankiBlacklistConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  ankiNeverForgetConfig: {
    deck: '',
    model: '',
    proxy: false,
    wordField: '',
    readingField: '',
    templateTargets: [],
  },
  ankiReadonlyConfigs: [],

  setSentences: false,

  hidePopupAutomatically: true,
  hidePopupDelay: 500,
  hideAfterAction: true,

  showPopupOnHover: false,
  touchscreenSupport: false,
  disableFadeAnimation: false,
  showParseButton: true,

  parseKey: [{ key: 'P', code: 'KeyP', modifiers: ['Alt'] }],
  showPopupKey: [{ key: 'Shift', code: 'ShiftLeft', modifiers: [] }],
  showAdvancedDialogKey: [],
  lookupSelectionKey: [{ key: 'L', code: 'KeyL', modifiers: ['Alt'] }],
  addToMiningKey: [],
  addToBlacklistKey: [],
  addToNeverForgetKey: [],
  addToSuspendedKey: [],

  customWordCSS: '',
  customPopupCSS: '',
});
