import { HostMeta } from './types';

export const DEFAULT_HOSTS: HostMeta[] = [
  {
    id: 'disable-crunchyroll',
    name: '_disable_crunchyroll_',
    host: '*://*.crunchyroll.com/*',
    auto: false,
    allFrames: false,
    disabled: true,
  },
  {
    id: 'trigger-parser',
    name: '_trigger_parser_',
    host: '<all_urls>',
    auto: false,
    allFrames: false,
    parse: 'body',
  },
  {
    id: 'kochounoyume-cde-parser',
    name: 'CDE Parser',
    host: [
      '*://jpdb.io/vocabulary/*',
      '*://jpdb.io/review*',
      '*://jpdb.io/deck*',
      '*://jpdb.io/search*',
    ],
    auto: true,
    optOut: true,
    allFrames: false,
    parserClass: 'kochounoyume-parser',
    parseVisibleObserver: {
      exclude: '.meaning-subsection-label',
    },
    addedObserver: {
      notifyFor: '.custom-dictionary-entry',
      observeFrom: 'body',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'texthooker-parser',
    name: 'Texthooker Parser',
    host: [
      '*://anacreondjt.gitlab.io/texthooker.html',
      '*://learnjapanese.moe/texthooker.html',
      '*://renji-xd.github.io/texthooker-ui/',
    ],
    auto: true,
    optOut: true,
    allFrames: false,
    parseVisibleObserver: true,
    parserClass: 'texthooker-parser',
    addedObserver: {
      notifyFor: '.textline, .line_box, .my-2.cursor-pointer, p',
      observeFrom: ['#textlog, main', 'body'],
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'exstatic-parser',
    name: 'ExStatic Parser',
    host: '*://kamwithk.github.io/exSTATic/tracker.html',
    auto: true,
    optOut: true,
    allFrames: false,
    parseVisibleObserver: true,
    custom: 'ExStaticParser',
    addedObserver: {
      notifyFor: '.sentence-entry',
      observeFrom: '#entry_holder',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'readwok-parser',
    name: 'Readwok Parser',
    host: '*://app.readwok.com/*',
    auto: true,
    optOut: true,
    allFrames: false,
    parseVisibleObserver: true,
    custom: 'ReadwokParser',
    addedObserver: {
      notifyFor: 'div[class*="styles_paragraph_"], div[class*="styles_reader_"]',
      observeFrom: 'body',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'ttsu-parser',
    name: 'Ttsu Parser',
    host: '*://reader.ttsu.app/*',
    auto: true,
    optOut: true,
    allFrames: false,
    custom: 'TtsuParser',
    parseVisibleObserver: true,
    addedObserver: {
      notifyFor: 'div.book-content',
      observeFrom: 'body',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'youtube-comments-parser',
    name: 'YouTube Comments Parser',
    host: ['*://*.youtube.com/*', '*://*.youtu.be/*'],
    auto: true,
    optOut: true,
    allFrames: false,
    parseVisibleObserver: true,
    parserClass: 'youtube-parser',
    addedObserver: {
      notifyFor: 'ytd-comment-view-model',
      observeFrom: 'body',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'mokuro-parser',
    name: 'Mokuro Parser',
    host: '*://reader.mokuro.app/*',
    auto: true,
    optOut: true,
    allFrames: true,
    custom: 'MokuroParser',
    parseVisibleObserver: true,
    addedObserver: {
      notifyFor: '#manga-panel',
      observeFrom: 'body',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'mokuro-legacy-parser',
    name: 'Mokuro Legacy Parser',
    host: 'file:///*mokuro*.html',
    auto: true,
    optOut: true,
    allFrames: true,
    custom: 'MokuroLegacyParser',
    parseVisibleObserver: true,
  },
  {
    id: 'wikipedia-parser',
    name: 'Wikipedia Parser',
    host: ['*://ja.wikipedia.org/*', '*://ja.m.wikipedia.org/*'],
    auto: true,
    optOut: true,
    allFrames: false,
    parserClass: 'wikipedia-parser',
    parseVisibleObserver: {
      exclude:
        '.p-lang-btn, .vector-menu-heading-label, .vector-toc-toggle, .vector-page-toolbar, .mw-editsection, sup.reference',
    },
    addedObserver: {
      notifyFor: '#firstHeading, #mw-content-text .mw-parser-output > *, .mwe-popups-extract > *',
      observeFrom: 'body',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
  {
    id: 'asbplayer-parser',
    name: 'asbplayer Parser',
    host: '<all_urls>',
    auto: true,
    optOut: true,
    allFrames: true,
    css: '.asbplayer-subtitles-container-bottom { z-index: 2147483646 }',
    parserClass: 'asb-player-parser',
    addedObserver: {
      notifyFor: '.asbplayer-offscreen',
      observeFrom: 'body',
      config: {
        childList: true,
        subtree: true,
      },
    },
  },
];
