name: Tagged Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
      - run: npm run lint
      - name: Build, lint, and publish Firefox to AMO (listed) + package Chromium
        run: npm run publish:ff
        env:
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/anki-jpdb.reader-chromium.zip
            packages/anki-jpdb.reader-firefox.xpi
            packages/LICENSE.md
